(ruby:rails:graphql:testmutation) scaffolding mutation test
Failures:

  1) Mutations::CreateUser.resolve creates a user
     Failure/Error:
       expect do
         post '/graphql', params: { query: _query }
       end.to change { ::User.count }.by(1)

       expected `::User.count` to have changed by 1, but was changed by 0
     # ./spec/graphql/mutations/create_user_spec.rb:9:in `block (3 levels) in <module:Mutations>'

  2) Mutations::CreateUser.resolve returns a book
     Failure/Error: data = json['data']['createUser']

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/graphql/mutations/create_user_spec.rb:19:in `block (3 levels) in <module:Mutations>'

Finished in 0.05815 seconds (files took 0.72928 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/graphql/mutations/create_user_spec.rb:6 # Mutations::CreateUser.resolve creates a user
rspec ./spec/graphql/mutations/create_user_spec.rb:14 # Mutations::CreateUser.resolve returns a book